version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./docker
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - ./code:/code
    ports:
      - "8888:8888"
    depends_on:
      - db
